version: '3'

services:
  docker-mysql:
    container_name: basededatos
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'animalfriends'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'pass'

  web1:
    container_name: web1
    image: jositote/animalfriends:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/animalfriends
    restart: always
    depends_on:
       - basededatos
       - correo
    
  web2:
    container_name: web2
    image: jositote/animalfriends:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/animalfriends
    restart: always
    depends_on:
       - basededatos
       - correo

  correo:
    container_name: correo
    image: jositote/correo:latest

  balanceador:
    container_name: hapro
    image: jositote/haproxy:latest
    restart: always
    ports: 
      - 80:80
      - 443:443
      - 8404:8404
    depends_on:
      - web1
      - web2