version: '3'

services:
  docker-mysql:
    container_name: basededatos
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'animalfriends'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - 3307:3306
      
  servicio-interno:
    container_name: rest
    image: jositote/rest:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/animalfriends
    restart: always
    depends_on:
      - animalfriends

  app:
    container_name: web1
    image: jositote/animalfriends:latest
    ports:
       - 8444:8443
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/animalfriends
    restart: always
    depends_on:
       - basededatos