FROM maven:3.8.5-openjdk-17 as builder
COPY . /code/
WORKDIR /code
RUN mvn package -DskipTests=true

FROM mysql
COPY ./database/ /docker-entrypoint-initdb.d/

FROM haproxy:1.7
COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg

FROM openjdk:11-jre
COPY --from=builder /code/target/*.jar /usr/app/
WORKDIR /usr/app
CMD [ "java", "-jar", "app.jar" ]