FROM maven:3.8.4-openjdk-17 as builder
WORKDIR /project
COPY /src /project/src
COPY pom.xml /project/
RUN mvn -B package -DskipTests=true

FROM openjdk:17-jdk-slim
WORKDIR /usr/src/app/
COPY --from=builder /project/target/*.jar /usr/src/app/correo.jar
CMD [ "java", "-jar", "correo.jar" ]